// automatically generated by the FlatBuffers compiler, do not modify

namespace Nostradamus.Examples.Schema
{

using System;
using FlatBuffers;

public struct MoveCharacterCommand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MoveCharacterCommand GetRootAsMoveCharacterCommand(ByteBuffer _bb) { return GetRootAsMoveCharacterCommand(_bb, new MoveCharacterCommand()); }
  public static MoveCharacterCommand GetRootAsMoveCharacterCommand(ByteBuffer _bb, MoveCharacterCommand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MoveCharacterCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float DeltaX { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float DeltaY { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<MoveCharacterCommand> CreateMoveCharacterCommand(FlatBufferBuilder builder,
      float deltaX = 0.0f,
      float deltaY = 0.0f) {
    builder.StartObject(2);
    MoveCharacterCommand.AddDeltaY(builder, deltaY);
    MoveCharacterCommand.AddDeltaX(builder, deltaX);
    return MoveCharacterCommand.EndMoveCharacterCommand(builder);
  }

  public static void StartMoveCharacterCommand(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDeltaX(FlatBufferBuilder builder, float deltaX) { builder.AddFloat(0, deltaX, 0.0f); }
  public static void AddDeltaY(FlatBufferBuilder builder, float deltaY) { builder.AddFloat(1, deltaY, 0.0f); }
  public static Offset<MoveCharacterCommand> EndMoveCharacterCommand(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MoveCharacterCommand>(o);
  }
};


}
