// automatically generated by the FlatBuffers compiler, do not modify

namespace Nostradamus.Schema
{

using System;
using FlatBuffers;

public struct KickBallCommand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static KickBallCommand GetRootAsKickBallCommand(ByteBuffer _bb) { return GetRootAsKickBallCommand(_bb, new KickBallCommand()); }
  public static KickBallCommand GetRootAsKickBallCommand(ByteBuffer _bb, KickBallCommand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public KickBallCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float InputX { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float InputY { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float InputZ { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<KickBallCommand> CreateKickBallCommand(FlatBufferBuilder builder,
      float inputX = 0.0f,
      float inputY = 0.0f,
      float inputZ = 0.0f) {
    builder.StartObject(3);
    KickBallCommand.AddInputZ(builder, inputZ);
    KickBallCommand.AddInputY(builder, inputY);
    KickBallCommand.AddInputX(builder, inputX);
    return KickBallCommand.EndKickBallCommand(builder);
  }

  public static void StartKickBallCommand(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddInputX(FlatBufferBuilder builder, float inputX) { builder.AddFloat(0, inputX, 0.0f); }
  public static void AddInputY(FlatBufferBuilder builder, float inputY) { builder.AddFloat(1, inputY, 0.0f); }
  public static void AddInputZ(FlatBufferBuilder builder, float inputZ) { builder.AddFloat(2, inputZ, 0.0f); }
  public static Offset<KickBallCommand> EndKickBallCommand(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<KickBallCommand>(o);
  }
};


}
