// automatically generated by the FlatBuffers compiler, do not modify

namespace Nostradamus.Examples.Schema
{

using System;
using FlatBuffers;

public struct CharacterMovedEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CharacterMovedEvent GetRootAsCharacterMovedEvent(ByteBuffer _bb) { return GetRootAsCharacterMovedEvent(_bb, new CharacterMovedEvent()); }
  public static CharacterMovedEvent GetRootAsCharacterMovedEvent(ByteBuffer _bb, CharacterMovedEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CharacterMovedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float PositionX { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PositionY { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<CharacterMovedEvent> CreateCharacterMovedEvent(FlatBufferBuilder builder,
      float positionX = 0.0f,
      float positionY = 0.0f) {
    builder.StartObject(2);
    CharacterMovedEvent.AddPositionY(builder, positionY);
    CharacterMovedEvent.AddPositionX(builder, positionX);
    return CharacterMovedEvent.EndCharacterMovedEvent(builder);
  }

  public static void StartCharacterMovedEvent(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPositionX(FlatBufferBuilder builder, float positionX) { builder.AddFloat(0, positionX, 0.0f); }
  public static void AddPositionY(FlatBufferBuilder builder, float positionY) { builder.AddFloat(1, positionY, 0.0f); }
  public static Offset<CharacterMovedEvent> EndCharacterMovedEvent(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CharacterMovedEvent>(o);
  }
};


}
