// automatically generated by the FlatBuffers compiler, do not modify

namespace Nostradamus.Schema
{

using System;
using FlatBuffers;

public struct ActorSnapshot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ActorSnapshot GetRootAsActorSnapshot(ByteBuffer _bb) { return GetRootAsActorSnapshot(_bb, new ActorSnapshot()); }
  public static ActorSnapshot GetRootAsActorSnapshot(ByteBuffer _bb, ActorSnapshot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ActorSnapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageEnvelope? Desc { get { int o = __p.__offset(4); return o != 0 ? (MessageEnvelope?)(new MessageEnvelope()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public MessageEnvelope? Args { get { int o = __p.__offset(6); return o != 0 ? (MessageEnvelope?)(new MessageEnvelope()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ActorSnapshot> CreateActorSnapshot(FlatBufferBuilder builder,
      Offset<MessageEnvelope> descOffset = default(Offset<MessageEnvelope>),
      Offset<MessageEnvelope> argsOffset = default(Offset<MessageEnvelope>)) {
    builder.StartObject(2);
    ActorSnapshot.AddArgs(builder, argsOffset);
    ActorSnapshot.AddDesc(builder, descOffset);
    return ActorSnapshot.EndActorSnapshot(builder);
  }

  public static void StartActorSnapshot(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDesc(FlatBufferBuilder builder, Offset<MessageEnvelope> descOffset) { builder.AddOffset(0, descOffset.Value, 0); }
  public static void AddArgs(FlatBufferBuilder builder, Offset<MessageEnvelope> argsOffset) { builder.AddOffset(1, argsOffset.Value, 0); }
  public static Offset<ActorSnapshot> EndActorSnapshot(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    builder.Required(o, 4);  // desc
    builder.Required(o, 6);  // args
    return new Offset<ActorSnapshot>(o);
  }
};


}
