// automatically generated by the FlatBuffers compiler, do not modify

namespace Nostradamus.Schema
{

using System;
using FlatBuffers;

public struct Login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Login GetRootAsLogin(ByteBuffer _bb) { return GetRootAsLogin(_bb, new Login()); }
  public static Login GetRootAsLogin(ByteBuffer _bb, Login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ClientId? ClientId { get { int o = __p.__offset(4); return o != 0 ? (ClientId?)(new ClientId()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Login> CreateLogin(FlatBufferBuilder builder,
      Offset<ClientId> clientIdOffset = default(Offset<ClientId>)) {
    builder.StartObject(1);
    Login.AddClientId(builder, clientIdOffset);
    return Login.EndLogin(builder);
  }

  public static void StartLogin(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddClientId(FlatBufferBuilder builder, Offset<ClientId> clientIdOffset) { builder.AddOffset(0, clientIdOffset.Value, 0); }
  public static Offset<Login> EndLogin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    builder.Required(o, 4);  // clientId
    return new Offset<Login>(o);
  }
};


}
