// automatically generated by the FlatBuffers compiler, do not modify

namespace Nostradamus.Schema
{

using System;
using FlatBuffers;

public struct SceneInitializedEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SceneInitializedEvent GetRootAsSceneInitializedEvent(ByteBuffer _bb) { return GetRootAsSceneInitializedEvent(_bb, new SceneInitializedEvent()); }
  public static SceneInitializedEvent GetRootAsSceneInitializedEvent(ByteBuffer _bb, SceneInitializedEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SceneInitializedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSceneInitializedEvent(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<SceneInitializedEvent> EndSceneInitializedEvent(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SceneInitializedEvent>(o);
  }
};


}
